services:
  heidar.ch:
    image: ghcr.io/arminheidarzadeh/heidar.ch:latest
    container_name: heidar.ch
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - heidar.ch

networks:
  heidar.ch:
    name: heidar.ch
